name: Publish OCI Image
on:
  push:
    branches:
      - main
    paths:
      - "rockcraft.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check the version
        id: get_version
        run: |
          sudo snap install yq --classic
          version="$(yq '.version' rockcraft.yaml)"
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Setup LXD
        uses: canonical/setup-lxd@v1

      - id: rockcraft
        name: Build ROCK
        run: |
          sudo snap install rockcraft --edge --classic
          rockcraft pack --verbose

      - name: Upload ROCK to ghcr.io
        run: |
          sudo skopeo --insecure-policy copy \
            "oci-archive:$(realpath ./upki-mirror_*.rock)" \
            "docker://ghcr.io/canonical/ubuntu-manpages-operator:${{ steps.get_version.outputs.VERSION }}" \
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"

          # Upload ROCK to ghcr.io/canonical/ubuntu-manpages-operator:latest
          sudo skopeo --insecure-policy copy \
            "oci-archive:$(realpath ./upki-mirror_*.rock)" \
            "docker://ghcr.io/canonical/ubuntu-manpages-operator:latest" \
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
